import type { Metadata } from 'next';
import { Inter, Poppins } from 'next/font/google';
import Footer from '~/core/components/common/footer';
import CommandMenuProvider from '~/core/components/common/header/commandMenu/CommandMenuProvider';
import Header from '~/core/components/ui/header';
import { cn } from '~/core/config/utils';
import StoreProvider from '~/core/providers/store-provider';
import '~/core/styles/globals.css';

const inter = Inter({ subsets: ['latin'] });

// TODO: Add metadata
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

const poppins = Poppins({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
  variable: '--font-poppins'
});

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='es'>
      <body className={cn(poppins.variable)}>
        <CommandMenuProvider>
          <StoreProvider>
            <Header />
            <div className='bg-[ #F8F9FA ] w-full font-poppins text-[#343A40]'>
              {children}
            </div>
            <Footer />
          </StoreProvider>
        </CommandMenuProvider>
      </body>
    </html>
  );
}
